# Generated by Django 4.2.7 on 2026-01-20 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(verbose_name='Bitiş Zamanı')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Amaç')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Araç Rezervasyonu',
                'verbose_name_plural': 'Araç Rezervasyonları',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='vehicleusage',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehiclereservation', verbose_name='Rezervasyon'),
        ),
    ]
