# Generated by Django 4.2.7 on 2026-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclereservation_vehicleusage_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='initial_kilometer',
            field=models.IntegerField(default=0, help_text='Aracın sisteme eklenirkenki kilometresi (ilk kullanımda bu değer kullanılır)', verbose_name='Başlangıç Kilometresi'),
        ),
    ]
