# Generated by Django 4.2.7 on 2026-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_initial_kilometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleusage',
            name='dropoff_location',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Ataşehir', 'Ataşehir'), ('Dilovası', 'Dilovası'), ('Tuzla', 'Tuzla')], max_length=50, null=True, verbose_name='Aracın Bırakıldığı Lokasyon'),
        ),
    ]
