# Generated by Django 4.2.7 on 2026-03-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicleusage_dropoff_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['location', 'plate'], 'verbose_name': 'Araç', 'verbose_name_plural': 'Araçlar'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(choices=[('Ataşehir', 'Ataşehir'), ('Dilovası', 'Dilovası')], default='Ataşehir', max_length=20, verbose_name='Lokasyon'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Araç Fotoğrafı'),
        ),
    ]
