# Generated by Django 4.2.7 on 2026-03-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_options_vehicle_location_vehicle_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Model Yılı')),
                ('color', models.CharField(blank=True, choices=[('Beyaz', 'Beyaz'), ('Siyah', 'Siyah'), ('Gri', 'Gri'), ('Gümüş', 'Gümüş'), ('Lacivert', 'Lacivert'), ('Mavi', 'Mavi'), ('Kırmızı', 'Kırmızı'), ('Bordo', 'Bordo'), ('Yeşil', 'Yeşil'), ('Sarı', 'Sarı'), ('Turuncu', 'Turuncu'), ('Kahverengi', 'Kahverengi'), ('Bej', 'Bej')], max_length=30, null=True, verbose_name='Renk')),
                ('owner_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Araç Sahibi/Şahıs')),
                ('user_company_department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kullanıcı Şirket / Departman')),
                ('user_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kullanıcı')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Muayene Tarihi')),
                ('insurance_end_date', models.DateField(blank=True, null=True, verbose_name='Sigorta Bitiş Tarihi')),
                ('casco_end_date', models.DateField(blank=True, null=True, verbose_name='Kasko Bitiş Tarihi')),
                ('last_maintenance_kilometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='En Son Bakım Kilometresi')),
                ('last_user_notes', models.TextField(blank=True, null=True, verbose_name='Son Kullanıcı')),
                ('tire_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lastik Ebatı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Zamanı')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Araç Tarihçesi',
                'verbose_name_plural': 'Araç Tarihçeleri',
            },
        ),
    ]
