# Generated by Django 4.2.7 on 2026-03-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehiclehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleExpiryNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('inspection', 'Muayene'), ('insurance', 'Sigorta'), ('casco', 'Kasko')], max_length=20, verbose_name='Kategori')),
                ('days_threshold', models.PositiveSmallIntegerField(verbose_name='Eşik (Gün)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Zamanı')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_notifications', to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Tarih Uyarısı',
                'verbose_name_plural': 'Tarih Uyarıları',
            },
        ),
        migrations.AddConstraint(
            model_name='vehicleexpirynotification',
            constraint=models.UniqueConstraint(fields=('vehicle', 'category', 'days_threshold'), name='uniq_vehicle_category_threshold'),
        ),
    ]
