# Generated by Django 4.2.7 on 2026-03-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicleexpirynotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='show_in_pool',
            field=models.BooleanField(default=True, verbose_name='Araç, havuzda listelensin mi?'),
        ),
        migrations.DeleteModel(
            name='VehicleExpiryNotification',
        ),
    ]
