# Generated by Django 4.2.7 on 2026-03-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_show_in_pool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleExpiryNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('inspection', 'Muayene'), ('insurance', 'Sigorta'), ('casco', 'Kasko')], max_length=20, verbose_name='Bildirim Türü')),
                ('target_date', models.DateField(help_text='Bildirim yapılan muayene/sigorta/kasko bitiş tarihi.', verbose_name='Hedef Tarih')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Zamanı')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_notifications', to='vehicles.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Araç Süre Bildirim Logu',
                'verbose_name_plural': 'Araç Süre Bildirim Logları',
                'ordering': ['-sent_at'],
                'unique_together': {('vehicle', 'notification_type', 'target_date')},
            },
        ),
    ]
