# Generated by Django 4.2.7 on 2026-03-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicleexpirynotificationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleExpiryNotificationLog',
        ),
    ]
