# Generated by Django 4.2.7 on 2026-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_delete_vehicleexpirynotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='operational_status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSIVE', 'Pasif')], default='ACTIVE', max_length=10, verbose_name='Araç Durumu'),
        ),
    ]
