# Generated by Django 4.2.7 on 2026-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_vehicle_operational_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duty',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Görev'),
        ),
    ]
