# Generated by Django 4.2.7 on 2026-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_user_duty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='location',
            field=models.CharField(
                choices=[
                    ('Ataşehir', 'Ataşehir'),
                    ('Dilovası', 'Dilovası'),
                    ('Tuzla', 'Tuzla'),
                    ('Santis Plaza', 'Santis Plaza'),
                ],
                default='Ataşehir',
                max_length=20,
                verbose_name='Lokasyon',
            ),
        ),
    ]
