# Generated by Django 4.2.7 on 2026-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_remove_vehicleusage_dropoff_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(
                choices=[('PERSONAL', 'Şahsi'), ('RENTAL', 'Kiralık')],
                default='PERSONAL',
                max_length=10,
                verbose_name='Araç Aidiyeti',
            ),
        ),
    ]
